version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./vaccinations.sql:/docker-entrypoint-initdb.d/vaccinations.sql
      - ./owners.sql:/docker-entrypoint-initdb.d/owners.sql
      - ./pets.sql:/docker-entrypoint-initdb.d/pets.sql
      - ./providers.sql:/docker-entrypoint-initdb.d/providers.sql
      - ./vaccinationRecords.sql:/docker-entrypoint-initdb.d/vaccinationRecords.sql
      - ./wallets.sql:/docker-entrypoint-initdb.d/wallets.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80