server:
  servlet:
    context-path: /petvax-services
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PETVAX
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
  security:
    user:
      name: user
      password: password
management:
  endpoints:
    web:
      base-path = /health
springfox.documentation.swagger-ui:
  path: /swagger-ui/index.html