server:
  servlet:
    context-path: /petvax-services
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PETVAX
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true